import type { LexSpec } from "./engine";

/** Generate a readable, plausible lex.yy.c for the given spec. */
export function generateC(spec: LexSpec): string {
  const tokenTypes = [...new Set(spec.rules.map((r) => r.tokenType).filter(Boolean))] as string[];

  const defines = tokenTypes.map((t, i) => `#define ${t} ${257 + i}`).join("\n");

  const caseArms = spec.rules
    .map((r, i) => {
      const act = r.action.replace(/\s+/g, " ").trim() || ";";
      return `        case ${i + 1}: /* ${r.pattern} */\n            ${act.endsWith(";") ? act : act + ";"}\n            break;`;
    })
    .join("\n");

  return `/* lex.yy.c — generated by flex (Lexora educational rendering)
 * ${spec.rules.length} rules, ${spec.definitions.length} named definitions
 * DFA: tables elided for readability; yy_accept maps states to rules. */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

${defines}

char *yytext;
int yyleng;
int yylineno = 1;

/* --- DFA tables (abbreviated) --------------------------------- */
static const short yy_accept[] = { 0, ${spec.rules.map((_, i) => i + 1).join(", ")} };
/* yy_nxt / yy_chk transition tables omitted — see the State panel
 * in the playground for the live automaton these encode. */

static int yy_scan(void);

int yylex(void) {
    for (;;) {
        int rule = yy_scan();          /* maximal munch over the DFA  */
        if (rule == 0) return 0;       /* EOF                         */
        switch (rule) {                /* rule actions, in priority   */
${caseArms}
        default:
            fprintf(stderr, "scanner jam near '%s'\\n", yytext);
            exit(1);
        }
    }
}

int yywrap(void) { return 1; }
`;
}
